{
    "category": "Exceptions",
    "name": "THROW",
    "tests":
    [
        {
            "script": "0xF0",
            "steps":
            [
                {
                    "actions":
                    [
                        "StepInto"
                    ],
                    "result":
                    {
                        "state": "Fault",
                        "invocationStack":
                        [
                            {
                                "scriptHash": "0x639095273057429f0475642a711b0ff24bee5f7d",
                                "instructionPointer": 1,
                                "nextInstruction": "RET"
                            }
                        ]
                    }
                }
            ]
        }
    ]
}